export const albums = [
  {
    id: "p0f9sqz8",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
  {
    id: "p0f9sqz8",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
  {
    id: "p0f9sqz8",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
  {
    id: "p0f9sqz8",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
  {
    id: "p0f9sqz8",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
  {
    id: "p0f9sqz8",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
  {
    id: "p0f9sqz8",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
  {
    id: "p0f9sqz8",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
  {
    id: "p0f9sqz8",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
  {
    id: "p0f9sqz8",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
  {
    id: "p0f9sqz8",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
];
