export const albums = [
  {
    id: "m0016pq3",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
    url: "https://www.bbc.co.uk/sounds/brand/m0016pq3?page=2",
  },
  {
    id: "m0016pq3",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
  {
    id: "m0016pq3",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
  {
    id: "m0016pq3",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
  {
    id: "m0016pq3",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
  {
    id: "m0016pq3",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
  {
    id: "m0016pq3",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
  {
    id: "m0016pq3",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
  {
    id: "m0016pq3",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
  {
    id: "m0016pq3",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
  {
    id: "m0016pq3",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
  {
    id: "m0016pq3",
    title: "Lady Killers with Lucy Worsley",
    cover: "",
    subtitle: "English Drama",
    date: "2022-12-12",
    time: "10:00",
    location: "101",
    description: "英语戏剧",
  },
];

export const episodes = [
  {
    id: "p0c24yk5",
    albumId: "m0016pq3",
    title: "Welcome to Lady Killers with Lucy Worsley",
    description:
      "Investigate the crimes of Victorian women, from a contemporary, feminist perspective.",
    date: "2022-12-12",
    time: "10:00",
  },
  {
    id: "m0016pq1",
    albumId: "m0016pq3",
    title: "1. Florence Bravo",
    description:
      "Lucy Worsley investigates a Victorian woman at the centre of a sensational poisoning.",
    date: "2022-12-12",
    time: "10:00",
  },
  {
    id: "m0016xqm",
    albumId: "m0016pq3",
    title: "2. Madeleine Smith",
    description: "Lucy Worsley investigates a secret love affair turned toxic.",
    date: "2022-12-12",
    time: "10:00",
  },
];
